apiVersion: v1
kind: Service
metadata:
  name: quizzler-service
  namespace: quizzler
spec:
  type: NodePort
  selector:
    app: quizzler
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000
